{
 "title": "IBP Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "prometheus" },
   {
    "name": "channel",
    "label": "Channel Name",
    "query": "label_values(ledger_blockchain_height,channel)"
   },
   {
    "name": "cc_name",
    "label": "Chaincode Name",
    "query": "label_values(chaincode_launch_duration_sum,chaincode)"
   },
   {
    "name": "couchdb_db",
    "label": "Peer CouchDB DB Name",
    "query": "label_values(couchdb_processing_time_sum,database)"
   }
  ]
 },
 "panels": [
  { "title": "Endorsement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "endorser_proposal_duration (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(endorser_propsal_duration_sum{chaincode=\"$cc_name\"}[1m])/rate(endorser_propsal_duration_count{chaincode=\"$cc_name\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "endorser_propsal_duration_count (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(endorser_propsal_duration_count{channel=\"$channel\",chaincode=\"$cc_name\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "endorser_proposals_received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "endorser_proposals_received\r", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "endorser_endorsement_failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "endorser_endorsement_failures\r\r{channel=\"$channel\",chaincode=\"$cc_name\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Ordering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "blockcutter_block_fill_duration (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "repeat": "channel",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(blockcutter_block_fill_duration_sum{channel=\"$channel\"}[1m])) / sum by (service) (rate(blockcutter_block_fill_duration_count{channel=\"$channel\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "consensus_etcdraft_data_persist_duration (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(consensus_etcdraft_data_persist_duration_sum[1m])) / sum by (service) (rate(consensus_etcdraft_data_persist_duration_count[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "consensus_etcdraft_leader_changes (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(consensus_etcdraft_leader_changes{channel=\"$channel\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Raft Cluster Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "consensus_etcdraft_cluster_size{channel=\"$channel\"}"
    }
   ]
  },
  {
   "title": "Raft Leader",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "consensus_etcdraft_is_leader{channel=\"$channel\"}==1"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "ledger_block_processing_time (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ledger_block_processing_time_sum{channel=\"$channel\"}[1m])/rate(ledger_block_processing_time_count{channel=\"$channel\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "ledger_blockstorage_commit_time (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(ledger_blockstorage_commit_time_sum[1m])) / sum by (service) (rate(ledger_blockstorage_commit_time_count[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "ledger_statedb_commit_time (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(ledger_statedb_commit_time_sum[1m])) / sum by (service) (rate(ledger_statedb_commit_time_count[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "ledger_transaction_count (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(ledger_transaction_count{channel=\"$channel\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "ledger_blockchain_height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "Block Height" }
   ],
   "targets": [
    {
     "expr": "ledger_blockchain_height{channel=\"$channel\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "couchdb_processing_time (rate 1min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(couchdb_processing_time_sum{database=\"$couchdb_db\"}[1m]))/ sum by (service) (rate(couchdb_processing_time_count{database =\"$couchdb_db\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Active GRPC connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_comm_conn_opened - grpc_comm_conn_closed",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "ledger_transaction_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ledger_transaction_count{transaction_type=\"ENDORSER_TRANSACTION\",channel=\"$channel\",chaincode=\"$cc_name\",validation_code=\"VALID\"}",
     "legendFormat": "{{service}} - {{validation_code}}"
    }
   ]
  },
  {
   "title": "gossip_leader_election_leader",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gossip_leader_election_leader{channel=\"$channel\"}==1"
    }
   ]
  },
  {
   "title": "Fabric Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "targets": [
    { "expr": "fabric_version", "legendFormat": "{{service}}" }
   ]
  }
 ]
}