apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    ibp: org1
  name: ibp-org1
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 30s
    port: https
    scheme: https
    path: /metrics
    targetPort: 9443
    tlsConfig:
      certFile: /etc/prometheus/secrets/org1-monitoring-secret/org1monitoring.pem
      keyFile: /etc/prometheus/secrets/org1-monitoring-secret/org1monitoring.key
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - ibp
  selector:
    matchLabels:
      app: ibp-org1-metrics
