apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    ibp: os
  name: ibp-os
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 30s
    port: https
    scheme: https
    path: /metrics
    targetPort: 8443
    tlsConfig:
      certFile: /etc/prometheus/secrets/os-operator-secret/operator.pem
      keyFile: /etc/prometheus/secrets/os-operator-secret/operator.key
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - ibp
  selector:
    matchLabels:
      app: ibp-os-metrics
