apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: ibp
  name: ibp
  namespace: openshift-monitoring
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: prometheus
              operator: In
              values:
              - ibp
          namespaces:
          - openshift-monitoring
          topologyKey: kubernetes.io/hostname
        weight: 100
  baseImage: registry.redhat.io/openshift3/prometheus
  containers:
  - args:
    - -provider=openshift
    - -https-address=:9091
    - -http-address=
    - -email-domain=*
    - -upstream=http://localhost:9090
    - -htpasswd-file=/etc/proxy/htpasswd/auth
    - -display-htpasswd-form=false
    - -openshift-service-account=prometheus-ibp
    - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
    - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
    - -tls-cert=/etc/tls/private/tls.crt
    - -tls-key=/etc/tls/private/tls.key
    - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -cookie-secret-file=/etc/proxy/secrets/session_secret
    - -openshift-ca=/etc/pki/tls/cert.pem
    - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - -skip-auth-regex=^/metrics
    image: registry.redhat.io/openshift3/oauth-proxy:v3.11.146
    name: prometheus-proxy
    ports:
    - containerPort: 9091
      name: web
    resources: {}
    volumeMounts:
    - mountPath: /etc/tls/private
      name: secret-prometheus-ibp-tls
    - mountPath: /etc/proxy/secrets
      name: secret-prometheus-ibp-proxy
    - mountPath: /etc/proxy/htpasswd
      name: secret-prometheus-ibp-htpasswd
  externalLabels:
    cluster: openshift.ocp1.169-56-56-187.nip.io
  externalUrl: http://prometheus-ibp-openshift-monitoring.apps.ocp1.169-56-56-187.nip.io/
  listenLocal: true
  replicas: 1
  resources: {}
  retention: 15d
  secrets:
  - prometheus-ibp-tls
  - prometheus-ibp-proxy
  - prometheus-ibp-htpasswd
  - os-monitoring-secret # Rename this is necessary
  - org1-monitoring-secret # Rename this is necessary
  securityContext: {}
  serviceAccountName: prometheus-ibp
  serviceMonitorNamespaceSelector:
    matchExpressions:
    - key: openshift-monitoring
      operator: Exists
  serviceMonitorSelector:
    matchExpressions:
    - key: ibp
      operator: Exists
  storage:
    resources: {}
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources:
          requests:
            storage: 30Gi
        storageClassName: portworx-sc
      status: {}
  tag: v3.11.141-2
  version: v2.3.2
