apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-ibp-tls
  labels:
    prometheus: ibp
  name: prometheus-ibp
  namespace: openshift-monitoring
spec:
  ports:
    - name: web
      port: 9091
      protocol: TCP
      targetPort: web
  selector:
    app: prometheus
    prometheus: ibp
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus-ibp
  namespace: openshift-monitoring
spec:
  port:
    targetPort: web
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: prometheus-ibp
    weight: 100
