apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.prometheus-ibp: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"prometheus-ibp"}}'
  name: prometheus-ibp
  labels:
    prometheus: ibp
  namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-ibp
  labels:
    prometheus: ibp
  namespace: openshift-monitoring
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - nodes/metrics
  verbs:
  - get
- apiGroups: null
  attributeRestrictions: null
  nonResourceURLs:
  - /metrics
  resources: []
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  attributeRestrictions: null
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  attributeRestrictions: null
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - get
- apiGroups: ["*"] #NEED TO LOCK THIS DOWN to Endpoints, Service and Pods only
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-ibp
  labels:
    prometheus: ibp
  namespace: openshift-monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-ibp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: prometheus-ibp
  namespace: openshift-monitoring
userNames:
- system:serviceaccount:openshift-monitoring:prometheus-ibp
---
apiVersion: v1
data:
  auth: aW50ZXJuYWw6e1NIQX1VMWJJT3VBYzBJOXR5QW9vRFF0enc3RDd3bmc9
kind: Secret
metadata:
  name: prometheus-ibp-htpasswd
  labels:
    prometheus: ibp
  namespace: openshift-monitoring
type: Opaque
---
apiVersion: v1
data:
  session_secret: YW9CU2dRazdxaWNkQmRJcndaYWZ3ZVI4cWN0bnlRcWZLN016Tks5bE5lNklpckt6SU1zMVczRGVyZz09
kind: Secret
metadata:
  name: prometheus-ibp-proxy
  labels:
    prometheus: ibp
  namespace: openshift-monitoring
type: Opaque

